apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: exercises
resources:
- ping_pong/manifests/service.yaml
- ping_pong/manifests/statefulset.yaml
- ping_pong/manifests/pingpong-postgres-config.yaml
- log_output/manifests/configMap.yaml
- log_output/manifests/deployment.yaml
- log_output/manifests/gateway.yaml
- log_output/manifests/route.yaml
- log_output/manifests/service.yaml
- greeter/manifests/greeter-dep.yaml
- greeter/manifests/http-route.yaml
- greeter/manifests/service.yaml
- greeter/manifests/namespace.yaml

images:
- name: HASH_GENERATOR
  newName: vesajo/hash-generator
  newTag: 11eb42d27fdb37b5c3c057b63f8760cd06bd1185
- name: HASH_OUTPUTTER
  newName: vesajo/hash-outputter
  newTag: 11eb42d27fdb37b5c3c057b63f8760cd06bd1185
- name: PING_PONG
  newName: vesajo/ping-pong
  newTag: 11eb42d27fdb37b5c3c057b63f8760cd06bd1185
