apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ping-pong-svc
  namespace: exercises
spec:
  template:
    spec:
      containers:
        - image: PING_PONG
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: pingpong-postgres-config
            - secretRef:
                name: pingpong-postgres-password
